exports.getComment = 'select * from commentdb where writing_no = ? and seq_no = ?'
exports.getCommentsForPost = 'select * from commentdb where writing_no = ?'
exports.getCommentsCountForPost = 'select count(*) as cnt from commentdb where writing_no = ?'
// exports.getCommentsCountForPosts = 'select writing_no, COUNT(*) AS cnt FROM commentdb where writing_no IN (?) group by writing_no'
exports.getCommentsForPostWithLimit = 'select * from commentdb where writing_no = ? limit ?, ?'
exports.insertComment = 'insert into commentdb(writing_no, mem_no, comment, comment_date) values(?,?,?,?)'
exports.deleteComment = 'delete from commentdb where seq_no = ? and mem_no = ?'
exports.deleteCommentWithWritingNo = 'delete from commentdb where writing_no = ?'